DrcVictim2/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrcVictim2.Models;
using DrcVictim2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VictimData;
using VictimData.Models;
using VictimData.Static;

namespace DrcVictim2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class DataController : Controller
    {
        private readonly IVictimAsset _service;
        private readonly IRegionAsset _serviceRegion;
        public DataController(IVictimAsset service,IRegionAsset serviceRegion)
        {
            _service = service;
            _serviceRegion = serviceRegion;
        }
        public async Task<IActionResult> Create()
        {

            var RegionDropdown = await _service.GetRegionDropdownValues();

            ViewBag.Regions = new SelectList(RegionDropdown.Regions, "RegionId", "Name");
           
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Create(Victim victims)
        {
            if (!ModelState.IsValid)
            {
                var RegionDropdown = await _service.GetRegionDropdownValues();
                ViewBag.Regions = new SelectList(RegionDropdown.Regions, "RegionId", "Name");
                return View(victims);
            }
            await _service.AddVictimsAsync(victims);
            return RedirectToAction("Index","Home",null,null);


        }
        [HttpGet]
        public IActionResult Region()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Region(Region region)
        {
            if (!ModelState.IsValid)
            {
               
                return View(region);
            }
            await _serviceRegion.AddRegionAsync(region);
            return RedirectToAction("Index", "Home", null, null);


        }

        // TO Finish the table
        [HttpGet]
        public IActionResult Victims()
        {
            var assetModel = _service.GettAllVictims();

          //  var region  = _service.


            var listingResult = assetModel.Select(result => new VictimVMAsset
            {
                City = result.City,
                 NumberofDeath  = result.NumberofDeath,
                 Source  = result.Source,
                 Rescue  = result.Rescue,
                 Region = (Region)_serviceRegion.GetRegion(result.RegionId),
                 VictimCategory  = (Models.VictimCategory)result.VictimCategory,
                 RegisteredDate  = result.RegisteredDate,


            });

            var model = new AssetIndexVictimVM()
            {
                Asset = listingResult
            };


            return View(model); 
        }

    }
}

DrcVictim2/Views/Shared/_Identity.cshtml
@if (User.Identity.IsAuthenticated)
{

    <div class=" dropdown">
        <button class=" btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge "></i>Hello
        </button>
        <ul class=" dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class=" dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class=" bi  bi-list">Orders</i>
                </a>
            </li>
        </ul>
    </div>
    <span style=" padding:5px;"></span>

    <form asp-controller="Account" asp-action="Logout">
        <button class=" btn btn-outline-danger my-2 my-sm-0">
            <i class=" bi bi-box-arrow-in-right">Log out</i>
        </button>
    </form>


}
else
{
    <a class="btn btn-outline-success my-2 my-sm-0" 
       asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>


    <span style=" padding:5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" 
       asp-controller="Account" asp-action="Register">
        <i class="bi bi-box-arrow-in-right"></i> Register
    </a>

    <span style=" padding:5px;"></span>

}

DrcVictim2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrcVictim2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DrcVictim2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Create"> Victim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Region"> Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="Victims"> Table</a>
                        </li>


                    </ul>

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DrcVictim2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)



            </body >
</html >